# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PFXRxSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PFXRxSwift
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxAlamofire'
  pod 'RxDataSources'
  pod 'RxOptional'


  target 'PFXRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PFXRxSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
